/*
 * Anchore Engine API Server
 *
 * This is the Anchore Engine API. Provides the primary external API for users of the service.
 *
 * API version: 0.1.5
 * Contact: nurmi@anchore.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package anchore_engine

// Filter for an image list by id, tag, or digest, but not both
type ImageFilter struct {
	Tag string `json:"tag,omitempty"`

	Digest string `json:"digest,omitempty"`
}
