/*
 * Anchore Engine API Server
 *
 * This is the Anchore Engine API. Provides the primary external API for users of the service.
 *
 * API version: 0.1.5
 * Contact: nurmi@anchore.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type MappingRule struct {

	Id string `json:"id,omitempty"`

	Name string `json:"name"`

	WhitelistIds []string `json:"whitelist_ids"`

	PolicyId string `json:"policy_id"`

	Registry string `json:"registry"`

	Repository string `json:"repository"`

	Image *ImageRef `json:"image"`
}
