/*
 * Anchore Engine API Server
 *
 * This is the Anchore Engine API. Provides the primary external API for users of the service.
 *
 * API version: 0.1.5
 * Contact: nurmi@anchore.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Policy struct {

	Id string `json:"id"`

	Name string `json:"name,omitempty"`

	Comment string `json:"comment,omitempty"`

	Version string `json:"version"`

	Rules []PolicyRule `json:"rules,omitempty"`
}
