/*
 * Anchore Engine API Server
 *
 * This is the Anchore Engine API. Provides the primary external API for users of the service.
 *
 * API version: 0.1.5
 * Contact: nurmi@anchore.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package anchore_engine

// A collection of whitelist items to match a policy evaluation against.
type Whitelist struct {
	Id string `json:"id"`

	Name string `json:"name,omitempty"`

	Version string `json:"version"`

	Comment string `json:"comment,omitempty"`

	Items []WhitelistItem `json:"items,omitempty"`
}
